import type { FullReport } from '@/common/types/vehicle.types';

/**
 * Hard-coded sample reports for demo/dev. Keyed by VIN.
 * Returned by VinService verbatim — bypasses providers and cache.
 * Remove or replace once a real Carfax/EpicVIN provider is wired in.
 */
export const MOCK_REPORTS: Record<string, Omit<FullReport, 'fetchedAt' | 'cached'>> = {
  ZASPAJAN5N7D24742: {
    vin: 'ZASPAJAN5N7D24742',
    decoded: {
      vin: 'ZASPAJAN5N7D24742',
      year: 2022,
      make: 'Alfa Romeo',
      model: 'Stelvio',
      trim: 'Sprint',
      bodyClass: '4 Door Wagon/Sport Utility',
      driveType: 'Rear wheel drive',
      engine: { cylinders: 4, displacementL: 2.0, fuelType: 'Gasoline' },
    },
    mileage: 38970,
    windowStickerUrl: '#',
    retailValue: { amount: 15840, currency: 'USD' },
    summary: {
      oilChangesRegular: true,
      openRecalls: 1,
      previousOwners: 2,
      useType: 'Personal',
      lastOwnedState: 'California',
      brandedTitle: true,
      salvage: true,
    },
    accidentEvents: [
      { index: 1, date: '2022-11-08', severity: 'minor', description: 'Damage reported: minor damage' },
      { index: 2, date: '2026-02-05', description: 'Damage reported' },
    ],
    serviceHighlights: [
      { date: '2025-09-29', service: 'Oil', comments: 'Oil and filter changed' },
    ],
    recalls: [
      {
        date: '2025-10-14',
        nhtsaId: '25V-667',
        recallNumber: 'A2C',
        description: '2020-2025 ALFA ROMEO GIULIA AND STELVIO RADIO BLAC',
        status: 'Remedy Available',
        source: 'FCA US LLC',
      },
    ],
    owners: [
      {
        index: 1,
        yearPurchased: 2022,
        type: 'Personal',
        lengthMonths: 14,
        states: ['California'],
        milesPerYear: 9087,
        lastOdometer: 10706,
        damageBrands: 'no_problem',
        odometerBrands: 'no_problem',
        additional: {
          totalLoss: 'no_issues',
          structuralDamage: 'no_issues',
          airbagDeployment: 'no_issues',
          odometerCheck: 'no_issues',
          accidentDamage: 'damage_reported',
          manufacturerRecall: 'no_recalls',
          basicWarranty: 'warranty_active',
        },
        events: [
          { source: 'FCA', comments: ['Original Window Sticker'] },
          {
            date: '2021-10-06',
            mileage: 10,
            source: 'Van Nuys Alfa Romeo Maserati',
            sourceLocation: 'Van Nuys, CA',
            sourceContact: '818-239-7081 · vannuysalfaromeo.com',
            rating: { stars: 4.1, count: 73 },
            comments: ['Vehicle serviced', 'Nitrogen fill tires'],
          },
          {
            date: '2022-01-03',
            mileage: 17,
            source: 'Los Angeles, California Motor Vehicle Dept.',
            sourceLocation: 'Los Angeles, CA',
            comments: ['Odometer reading reported'],
          },
          {
            date: '2022-01-21',
            source: 'Los Angeles, California Motor Vehicle Dept.',
            sourceLocation: 'Los Angeles, CA',
            comments: [
              'Title issued or updated',
              'First owner reported',
              'Titled or registered as personal vehicle',
              'Loan or lien reported',
            ],
          },
          {
            date: '2022-04-25',
            source: 'Los Angeles, California Motor Vehicle Dept.',
            sourceLocation: 'Los Angeles, CA',
            comments: ['Title issued or updated', 'Loan or lien reported'],
          },
          {
            date: '2022-11-08',
            source: 'Damage Report',
            damage: { severity: 'minor', location: 'front', description: 'Damage reported: minor damage. Damage to front.' },
            comments: ['Damage reported: minor damage', 'Damage to front'],
          },
          {
            date: '2023-02-07',
            mileage: 8947,
            source: 'Van Nuys Alfa Romeo Maserati',
            sourceLocation: 'Van Nuys, CA',
            sourceContact: '818-239-7081 · vannuysalfaromeo.com',
            rating: { stars: 4.1, count: 73 },
            comments: [
              'Vehicle serviced',
              'Maintenance inspection completed',
              '10,000 mile service performed',
              'Oil and filter changed',
              'Tire condition and pressure checked',
            ],
          },
          {
            date: '2023-03-23',
            source: 'Online Listing',
            comments: ['Vehicle offered for sale'],
          },
          {
            date: '2023-03-27',
            mileage: 10706,
            source: 'Auto Auction',
            comments: ['Vehicle sold'],
          },
        ],
      },
      {
        index: 2,
        yearPurchased: 2023,
        type: 'Personal',
        lengthMonths: 33,
        states: ['California'],
        milesPerYear: 12349,
        lastOdometer: 38970,
        damageBrands: 'alert',
        odometerBrands: 'no_problem',
        additional: {
          totalLoss: 'no_issues',
          structuralDamage: 'no_issues',
          airbagDeployment: 'no_issues',
          odometerCheck: 'no_issues',
          accidentDamage: 'severe_damage',
          manufacturerRecall: 'recall_reported',
          basicWarranty: 'warranty_voided',
        },
        events: [
          {
            date: '2023-06-18',
            mileage: 10753,
            source: 'Irvine, California Motor Vehicle Dept.',
            sourceLocation: 'Irvine, CA',
            comments: ['Odometer reading reported'],
          },
          {
            date: '2023-07-14',
            source: 'Irvine, California Motor Vehicle Dept.',
            sourceLocation: 'Irvine, CA',
            comments: ['Title issued or updated', 'New owner reported', 'Loan or lien reported'],
          },
          {
            date: '2023-12-06',
            mileage: 17214,
            source: 'Big Brand Tire',
            sourceLocation: 'Irvine, CA',
            sourceContact: '949-774-4797 · bigbrandtire.com',
            rating: { stars: 4.3, count: 72 },
            comments: ['Vehicle serviced', 'Oil and filter changed', 'Tire repaired', 'Tires rotated'],
          },
          {
            date: '2024-11-22',
            mileage: 28050,
            source: 'Maserati of Anaheim Hills',
            sourceLocation: 'Yorba Linda, CA',
            sourceContact: '866-780-9313 · maseratiofanaheimhills.com',
            rating: { stars: 4.6, count: 180 },
            comments: [
              'Vehicle serviced',
              'Maintenance inspection completed',
              'A/C and heating system checked',
              'Blower motor replaced/repaired',
              'Oil and filter changed',
              'Tire condition and pressure checked',
              'Window(s) checked',
            ],
          },
          {
            date: '2025-09-29',
            mileage: 38970,
            source: 'Euro Car Doctor',
            sourceContact: '949-474-4555 · eurocardoctor.com',
            rating: { stars: 4.9, count: 56 },
            comments: [
              'Vehicle serviced',
              'Maintenance inspection completed',
              'Body lubricated',
              'Fluids checked',
              'Maintenance reminder reset',
              'Oil and filter changed',
              'Tire condition and pressure checked',
            ],
          },
          {
            date: '2025-10-14',
            source: 'FCA US LLC',
            comments: [
              'Manufacturer Safety recall issued',
              'NHTSA #25V-667',
              'Recall #A2C 2020-2025 ALFA ROMEO GIULIA AND STELVIO RADIO BLAC',
              'Status: Remedy Available',
            ],
          },
          {
            date: '2026-02-05',
            source: 'Damage Report',
            damage: { location: 'front', description: 'Damage reported. Damage to front.' },
            comments: ['Damage reported', 'Damage to front'],
          },
          {
            date: '2026-03-13',
            source: 'Irvine, California Motor Vehicle Dept.',
            sourceLocation: 'Irvine, CA',
            comments: ['Title issued or updated', 'Loan or lien reported'],
          },
          {
            date: '2026-03-24',
            source: 'Damage Report',
            comments: ['SALVAGE TITLE/CERTIFICATE ISSUED'],
          },
        ],
      },
    ],

    // Legacy fields kept for backward-compat with the existing API contract.
    // Aggregated from the rich data above so basic clients still see something.
    history: [
      { date: '2022-11-08', type: 'accident', source: 'mock', description: 'Minor damage to front' },
      { date: '2026-02-05', type: 'accident', source: 'mock', description: 'Damage to front' },
      { date: '2023-03-27', type: 'auction', source: 'mock', mileage: 10706, description: 'Vehicle sold at auction' },
      { date: '2026-03-24', type: 'title', source: 'mock', description: 'Salvage title/certificate issued' },
    ],
    salvage: [],
    images: [],
    providers: ['sample'],
  },
};
